# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4790b0a6c2c0d77211a83596cadd82cfd04f4efe16aaecc3f8068adf75a9a802d076eb31652139e82e407529640c68741bf9d4f299e97bc8bcd86a5421e3fef6

test:
  secret_key_base: 2bc8555fb393c92401dcfcbb7bf6a5047ece3487647e7be232b3ac5c7e626598858e9c5fbcc4d71b6001686712dbe5d90a71ddca6044565aad61daaccc882d02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
